# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
  name: default

variables:
  major: 1
  minor: 1
  patch: $[counter(variables['minor'], 0)]
  NugetVersion: $(major).$(minor).$(patch)
  TagVersion: $(NugetVersion)-tt

steps:
- task: Bash@3
  displayName: "versioning"
  inputs:
    targetType: inline
    script: |
          echo 'VERSION ' $VERSION
          if [ $(Build.SourceBranchName) = "master" ]; then
            VERSION=$(NugetVersion)
          else
            VERSION=$(NugetVersion)-beta
          fi;
          set $(TagVersion)=$VERSION

- task: Bash@3
  displayName: "Adding git"
  inputs:
    targetType: inline
    script: |
            git tag $(TagVersion) $(Build.SourceVersion)
            git push $(Build.SourceBranchName) $(TagVersion)